Repository ButterCam/sisyphus, pull requests merged in 2020-05, with the labels that each got.

#2 Fix errors and bugs in internal usage
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/publishplugins.yml
  ReadMe.md
  lib/sisyphus-dto/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module
  lib/sisyphus-grpc/src/main/proto/sisyphus/api/paging/paging.proto
  lib/sisyphus-grpc/src/main/proto/sisyphus/api/service_meta.proto
  middleware/sisyphus-configuration-artifact/src/main/kotlin/com/bybutter/sisyphus/middleware/configuration/SisyphusProperty.kt
  starter/sisyphus-grpc-server-starter/src/main/resources/META-INF/spring.factories
Labels: bug, documentation

#3 Skip publish to internal nexus
  .github/workflows/publish.yml
Labels: CI

#4 Fix 'ConditionalOnMissingBean' not work with component scan
  middleware/sisyphus-amqp/src/main/kotlin/com/bybutter/sisyphus/middleware/amqp/DefaultAmqpTemplateFactory.kt
  middleware/sisyphus-amqp/src/main/kotlin/com/bybutter/sisyphus/middleware/amqp/SisyphusAmqpAutoConfiguration.kt
  middleware/sisyphus-elastic/src/main/kotlin/com/bybutter/sisyphus/middleware/elastic/DefaultElasticClientFactory.kt
  middleware/sisyphus-elastic/src/main/kotlin/com/bybutter/sisyphus/middleware/elastic/SisyphusElasticAutoConfiguration.kt
  middleware/sisyphus-hbase/src/main/kotlin/com/bybutter/sisyphus/middleware/hbase/DefaultHBaseTemplateFactory.kt
  middleware/sisyphus-hbase/src/main/kotlin/com/bybutter/sisyphus/middleware/hbase/SisyphusHBaseAutoConfiguration.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/DefaultDslContextFactory.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/SisyphusJdbcAutoConfiguration.kt
  middleware/sisyphus-jdbc/src/test/kotlin/com/bybutter/sisyphus/middleware/jdbc/test/EmbeddedDatasourceConfig.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/DefaultRedisClientFactory.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/SisyphusRedisAutoConfiguration.kt
  starter/sisyphus-jackson-starter/src/main/kotlin/com/bybutter/sisyphus/starter/jackson/SisyphusJacksonAutoConfiguration.kt
  starter/sisyphus-jackson-starter/src/main/kotlin/com/bybutter/sisyphus/starter/jackson/cbor/Jackson2CborCodecCustomizer.kt
  starter/sisyphus-jackson-starter/src/main/kotlin/com/bybutter/sisyphus/starter/jackson/json/Jackson2JsonCodecCustomizer.kt
  starter/sisyphus-jackson-starter/src/main/kotlin/com/bybutter/sisyphus/starter/jackson/smile/Jackson2SmileCodecCustomizer.kt
  starter/sisyphus-jackson-starter/src/main/kotlin/com/bybutter/sisyphus/starter/jackson/yaml/Jackson2YamlCodecCustomizer.kt
Labels: bug, ready to merge

#6 Support graceful shutdown for gRPC server
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/ServerLifecycle.kt
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/ServerRunner.kt
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/ServiceRegistrar.kt
  starter/sisyphus-webflux-starter/src/main/kotlin/com/bybutter/sisyphus/starter/webflux/AutoGracefulShutdownConfigurator.kt
  starter/sisyphus-webflux-starter/src/main/resources/META-INF/spring.factories
Labels: enhancement

#5 Support autoconfig for docker plugin
  .github/workflows/build.yml
  .github/workflows/publish.yml
  dependencies/build.gradle.kts
  tools/sisyphus-project-gradle-plugin/build.gradle.kts
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/SisyphusExtension.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/SisyphusProjectPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/Utils.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/java/JavaBaseProjectPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/java/JavaLibraryProjectPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/java/JavaPlatformProjectPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/publishing/ProjectContactsPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/publishing/ProjectLicensePlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/publishing/ProjectPublishingPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/publishing/ProjectSigningPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/threepart/SisyphusAntlrKotlinPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/threepart/SisyphusDockerPlugin.kt
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/threepart/SisyphusKtlintPlugin.kt
Labels: code quality, enhancement

#17 Generate gRPC service and client based on grpc-kotlin
  .github/workflows/build.yml
  .github/workflows/publish.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/dependencies.kt
  dependencies/build.gradle.kts
  lib/sisyphus-grpc/build.gradle.kts
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/Adpter.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/ClientCalls.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/GrpcContextCoroutineContextElement.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/GrpcServerConstants.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/ManyToManyCall.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/ManyToOneCall.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/Sender.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/ServerCallHandlers.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/ServiceSupport.kt
  lib/sisyphus-protobuf/build.gradle.kts
  middleware/sisyphus-grpc-client/build.gradle.kts
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ClientRegistrar.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/GrpcChannelProperty.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/GrpcClientProxy.kt
  middleware/sisyphus-grpc-client/src/test/kotlin/com/bybutter/sisyphus/middleware/grpc/test/RegisterTest.kt
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/ServiceRegistrar.kt
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/SisyphusGrpcServerAutoConfiguration.kt
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/support/ReflectionService.kt
  starter/sisyphus-grpc-server-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/support/ReflectionServiceAlpha.kt
  starter/sisyphus-grpc-server-starter/src/test/kotlin/com/bybutter/sisyphus/starter/grpc/test/RegisterTest.kt
  starter/sisyphus-grpc-server-starter/src/test/proto/service_test.proto
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/Utils.kt
  tools/sisyphus-protoc/src/main/kotlin/com/bybutter/sisyphus/protobuf/compiler/FileGenerator.kt
  tools/sisyphus-protoc/src/main/kotlin/com/bybutter/sisyphus/protobuf/compiler/ServiceGenerator.kt
  tools/sisyphus-protoc/src/main/kotlin/com/bybutter/sisyphus/protobuf/compiler/ServiceMethodGenerator.kt
Labels: enhancement

#19 Fix Swagger bug.
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/swagger/SwaggerRouterFunction.kt
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/swagger/utils/SwaggerPaths.kt
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/swagger/utils/SwaggerSchema.kt
Labels: ready to merge
