Repository ButterCam/sisyphus, pull requests merged in 2020-09, with the labels that each got.

#69 :bug: Fixed jooq page util bug
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/utils/Page.kt
Labels: bug

#70 :sparkles: Auto configure transitive dependencies for proto configuration
  tools/sisyphus-protobuf-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/protobuf/gradle/ProtobufPlugin.kt
Labels: enhancement

#73 :sparkles: Support intercepting call options
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/CallOptionsInterceptor.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/Debug.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/rpc/SisyphusStub.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ClientRegistrar.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/LocalClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/RemoteClientRepository.kt
  tools/sisyphus-protoc/src/main/kotlin/com/bybutter/sisyphus/protobuf/compiler/ServiceGenerator.kt
  tools/sisyphus-protoc/src/main/kotlin/com/bybutter/sisyphus/protobuf/compiler/ServiceMethodGenerator.kt
Labels: enhancement

#82 :art: Modify middleware name to qualifier annotation
  middleware/sisyphus-elastic/src/main/kotlin/com/bybutter/sisyphus/middleware/elastic/ElasticClientRegistrar.kt
  middleware/sisyphus-elastic/src/main/kotlin/com/bybutter/sisyphus/middleware/elastic/ElasticProperty.kt
  middleware/sisyphus-hbase/src/main/kotlin/com/bybutter/sisyphus/middleware/hbase/HBaseTableProperty.kt
  middleware/sisyphus-hbase/src/main/kotlin/com/bybutter/sisyphus/middleware/hbase/HTableTemplateRegistrar.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/AbstractDslContextFactory.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/DslContextFactory.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/DslContextRegistrar.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/JdbcDatabaseProperty.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/JooqConfigInterceptor.kt
  middleware/sisyphus-jdbc/src/main/kotlin/com/bybutter/sisyphus/middleware/jdbc/SpringJooqConfigurationAdapter.kt
  middleware/sisyphus-jdbc/src/test/kotlin/com/bybutter/sisyphus/middleware/jdbc/test/EmbeddedDatasourceConfig.kt
  middleware/sisyphus-jdbc/src/test/kotlin/com/bybutter/sisyphus/middleware/jdbc/test/Jdbc.kt
  middleware/sisyphus-jdbc/src/test/kotlin/com/bybutter/sisyphus/middleware/jdbc/test/TransactionTest.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/RedisConnectionRegistrar.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/RedisProperty.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/cache/config/MultiCacheConfig.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/cache/config/PointcutAdvisor.kt
Labels: ready to merge

#81 :sparkles: Supported RocketMQ Ons
  buildSrc/src/main/kotlin/dependencies.kt
  dependencies/build.gradle.kts
  middleware/sisyphus-rocketmq-ons/build.gradle.kts
  middleware/sisyphus-rocketmq-ons/src/main/kotlin/com/bybutter/sisyphus/middleware/rocketmq/DefaultRocketTemplateFactory.kt
  middleware/sisyphus-rocketmq-ons/src/main/kotlin/com/bybutter/sisyphus/middleware/rocketmq/RocketMQProperty.kt
  middleware/sisyphus-rocketmq-ons/src/main/kotlin/com/bybutter/sisyphus/middleware/rocketmq/RocketTemplateFactory.kt
  middleware/sisyphus-rocketmq-ons/src/main/kotlin/com/bybutter/sisyphus/middleware/rocketmq/autoconfigure/RocketMQRegistrar.kt
  middleware/sisyphus-rocketmq-ons/src/main/kotlin/com/bybutter/sisyphus/middleware/rocketmq/autoconfigure/SisyphusRocketAutoConfiguration.kt
  middleware/sisyphus-rocketmq-ons/src/main/resources/META-INF/spring.factories
  settings.gradle.kts
Labels: ready to merge
