Repository ButterCam/sisyphus, pull requests merged in 2020-07, with the labels that each got.

#39 Add channel lifecycle
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ClientRegistrar.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/LocalClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ManagedChannelLifecycle.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/RemoteClientRepository.kt
Labels: bug, ready to merge

#41 Fix repeated custom type can't be converted in message patcher
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/MessagePatcher.kt
Labels: bug, ready to merge

#42 Add kubernetes label auto register [service-discovery]
  middleware/sisyphus-grpc-client-kubernetes/build.gradle.kts
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/EnableKubernetesServiceDiscovery.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesClientRepository.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesLabelAutoRegister.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/support/Patch.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/support/PatchOperateType.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/support/ServiceLabelPatch.kt
Labels: enhancement, ready to merge

#43 Fix serializing for map with google.protobuf.Any value
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/jackson/ProtoSerializer.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/primitives/AnyExtension.kt
  lib/sisyphus-protobuf/src/test/kotlin/com/bybutter/sisyphus/protobuf/test/ProtoTest.kt
  lib/sisyphus-protobuf/src/test/proto/test.proto
Labels: bug, ready to merge

#45 Make api linter working with windows
  tools/sisyphus-api-linter-runner/src/main/kotlin/com/bybutter/sisyphus/apilinter/ApiLinterRunner.kt
  tools/sisyphus-protobuf-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/protobuf/gradle/ExtractProtoTask.kt
Labels: bug

#50 Publish to gradle portal when release
  .github/workflows/publish.yml
Labels: CI

#51 Make api linter runner as simple java library
  tools/sisyphus-api-linter-runner/build.gradle.kts
Labels: CI

#52 Add zoneId parameter for create timestamp
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/primitives/TimestampExtension.kt
Labels: enhancement

#53 Throw exception when running cel with syntax error
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/api/filtering/FilterSyntaxErrorListener.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/api/filtering/FilterSyntaxException.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/api/filtering/MessageFilter.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/cel/CelEngine.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/cel/CelErrorListener.kt
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/cel/CelSyntaxException.kt
Labels: enhancement

#49 Add unit tests for sisyphus-grpc cel module
  build.gradle.kts
  lib/sisyphus-grpc/src/main/kotlin/com/bybutter/sisyphus/cel/CelStandardLibrary.kt
  lib/sisyphus-grpc/src/test/kotlin/com/bybutter/sisyphus/cel/test/CelEngineTest.kt
  lib/sisyphus-grpc/src/test/proto/sisyphus/api/cel/test/cel_test.proto
  settings.gradle.kts
Labels: test

#54 Add gradle and jdk badge
  ReadMe.md
Labels: documentation

#60 :sparkles: Support configure database for redis
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/DefaultRedisClientFactory.kt
  middleware/sisyphus-redis/src/main/kotlin/com/bybutter/sisyphus/middleware/redis/RedisProperty.kt
Labels: enhancement
