Repository ButterCam/sisyphus, pull requests merged in 2020-06, with the labels that each got.

#21 Add defer logger for 'ConfigArtifactProvider'
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/jackson/ProtoDeserializer.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/jackson/ProtoSerializer.kt
  middleware/sisyphus-configuration-artifact/src/main/kotlin/com/bybutter/sisyphus/middleware/configuration/ConfigArtifactProvider.kt
  middleware/sisyphus-configuration-artifact/src/main/resources/META-INF/spring.factories
Labels: bug, enhancement, ready to merge

#22 Add 'grpc-service-name' header for http transcoding method signing.
  lib/sisyphus-grpc/src/main/proto/sisyphus/api/service_meta.proto
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/TranscodingRouterFunction.kt
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/TranscodingServiceRouterFunction.kt
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/swagger/SwaggerRouterFunction.kt
  starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/swagger/utils/SwaggerParams.kt
Labels: enhancement, ready to merge

#23 Support 'BUILD_VERSION' env for customizing version
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/SisyphusExtension.kt
Labels: enhancement

#24 Change swagger resources path
  starter/sisyphus-grpc-transcoding-starter/src/main/resources/META-INF/services/com.bybutter.middleware.config.ConfigArtifactPropertyExporter
  starter/sisyphus-grpc-transcoding-starter/src/main/resources/META-INF/services/com.bybutter.sisyphus.middleware.configuration.ConfigArtifactPropertyExporter
Labels: ready to merge

#25 Fix license plugin github repo assembling
  tools/sisyphus-project-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/project/gradle/publishing/ProjectLicensePlugin.kt
Labels: bug, ready to merge

#27 Simple quick start document
  ReadMe.md
Labels: documentation

#35 Publish artifact to Github Package
  .github/workflows/publish.yml
Labels: CI

#36 Fix github url for gradle publish
  .github/workflows/publish.yml
Labels: CI

#37 Disable publish to Github Package
  .github/workflows/publish.yml
Labels: CI

#34 Fixed service discovery bugs
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesClientRepository.kt
  middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/ClientRegistrar.kt
Labels: bug, ready to merge

#38 Build release when a pre-release is changed to a release
  .github/workflows/publish.yml
Labels: CI
