Repository ButterCam/sisyphus, pull requests merged in 2021-03, with the labels that each got.

#171 :bug: Fix member context filter is empty string
  lib/sisyphus-dsl/src/main/kotlin/com/bybutter/sisyphus/dsl/filtering/MemberContext.kt
Labels: bug

#194 :sparkles: Add more extension function for parse json
  lib/sisyphus-jackson/src/main/kotlin/com/bybutter/sisyphus/jackson/Json.kt
Labels: enhancement

#193 :bug: Use api configuration for resolve proto api configuration
  tools/sisyphus-protobuf-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/protobuf/gradle/ProtobufJvmPlugin.kt
  tools/sisyphus-protobuf-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/protobuf/gradle/ProtobufPlugin.kt
  tools/sisyphus-protobuf-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/protobuf/gradle/Util.kt
Labels: bug, hot fix

#198 :bug: Fix kubernetes service name bug
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesClientRepository.kt
Labels: bug, hot fix

#197 :bug: Fix test classpath not contains main resource
  tools/sisyphus-protobuf-gradle-plugin/src/main/kotlin/com/bybutter/sisyphus/protobuf/gradle/ProtobufJvmPlugin.kt
Labels: bug, hot fix

#200 Update test file for sisyphus-test
  lib/sisyphus-test/build.gradle.kts
  lib/sisyphus-test/src/main/kotlin/com/bybutter/sisyphus/test/JsonArgumentsProvider.kt
  lib/sisyphus-test/src/main/kotlin/com/bybutter/sisyphus/test/JsonFileArgumentsProvider.kt
  lib/sisyphus-test/src/main/kotlin/com/bybutter/sisyphus/test/JsonFileSource.kt
  lib/sisyphus-test/src/main/kotlin/com/bybutter/sisyphus/test/JsonSource.kt
  lib/sisyphus-test/src/main/kotlin/com/bybutter/sisyphus/test/Runner.kt
  lib/sisyphus-test/src/main/kotlin/com/bybutter/sisyphus/test/TestReporter.kt
  lib/sisyphus-test/src/main/proto/sisyphus/test/case.proto
  lib/sisyphus-test/src/test/kotlin/com/bybutter/sisyphus/test/test/JsonFileArgumentsProviderTest.kt
  lib/sisyphus-test/src/test/kotlin/com/bybutter/sisyphus/test/test/api/TestApiImpl.kt
  lib/sisyphus-test/src/test/proto/api_test.proto
  lib/sisyphus-test/src/test/resources/json-file-test.json
  settings.gradle.kts
Labels: test

#202 :zap: Lazy initialize unknownFields and extensions
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/AbstractMessage.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/AbstractMutableMessage.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/UnknownField.kt
  middleware/sisyphus-grpc-client-kubernetes/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/client/kubernetes/KubernetesClientRepository.kt
Labels: enhancement

#209 :zap: Use stream writer for improve message serialize performance
  lib/sisyphus-common/src/main/kotlin/com/bybutter/sisyphus/data/Varint.kt
  lib/sisyphus-common/src/main/kotlin/com/bybutter/sisyphus/io/FixedByteArrayOutputStream.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/AbstractMessage.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/coded/MeasureWriter.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/coded/PredictWriter.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/coded/Reader.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/coded/StreamWriter.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/coded/WireType.kt
  lib/sisyphus-protobuf/src/main/kotlin/com/bybutter/sisyphus/protobuf/coded/Writer.kt
  lib/sisyphus-protobuf/src/test/kotlin/com/bybutter/sisyphus/protobuf/test/ProtoTest.kt
Labels: enhancement

#212 :apple: Add Apple silicon support for protobuf compiler
  buildSrc/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  tools/sisyphus-protoc/src/main/kotlin/com/bybutter/sisyphus/protobuf/compiler/ProtocRunner.kt
Labels: enhancement
